### PR TITLE
feat: Add `/webrtc` protocol (browser-to-browser)

### PR DESCRIPTION
**Pull request by mxinden**

### CODE REVIEW

**Comment by mxinden** [comment]
Should we introduce this in the version after https://github.com/multiformats/rust-multiaddr/pull/78? The version that includes https://github.com/multiformats/rust-multiaddr/pull/78 only would then error on `/webrtc` instead of interpreting it as the browser-to-browser protocol. Might prevent some confusion.

**Comment by thomaseizinger** [comment]
> Should we introduce this in the version after #78? The version that includes #78 only would then error on `/webrtc` instead of interpreting it as the browser-to-browser protocol. Might prevent some confusion.

It is frustrating to release so many breaking changes but I don't think there is much choice now that the decision has been made.

**Comment by mxinden** [comment]
Moving to draft in order to not include in `v0.18.0`.

**Comment by jxs** [comment]
superseeded by #110

**Pull request closed without merging**
