### PR TITLE
Update CID to 0.4.

### LINKED ISSUE #38: Build fails on rust stable due to CID crate
```
$ cargo --version
cargo 1.42.0 (86334295e 2020-01-31)
$ git rev-parse --short HEAD
9682623
$ cargo build
   Compiling multiaddr v0.3.1 (/Users/jameshageman/Documents/Github/school/fydp/rust-multiaddr)
warning: trait objects without an explicit `dyn` are deprecated
  --> src/errors.rs:13:22
   |
13 |     ParsingError(Box<error::Error + Send + Sync>),
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn error::Error + Send + Sync`
   |
   = note: `#[warn(bare_trait_objects)]` on by default

warning: trait objects without an explicit `dyn` are deprecated
  --> src/errors.rs:34:32
   |
34 |     fn cause(&self) -> Option<&error::Error> {
   |                                ^^^^^^^^^^^^ help: use `dyn`: `dyn error::Error`

warning: use of deprecated item 'std::error::Error::description': use the Display impl or to_string()
  --> src/errors.rs:18:21
   |
18 |         f.write_str(error::Error::description(self))
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

error[E0277]: the trait bound `cid::Error: std::error::Error` is not satisfied
  --> src/errors.rs:50:33
   |
50 |         Error::ParsingError(err.into())
   |                                 ^^^^ the trait `std::error::Error` is not implemented for `cid::Error`
   |
   = note: required because of the requirements on the impl of `std::convert::From<cid::Error>` for `std::boxed::Box<dyn std::error::Error + std::marker::Send + std::marker::Sync>`
   = note: required because of the requirements on the impl of `std::convert::Into<std::boxed::Box<dyn std::error::Error + std::marker::Send + std::marker::Sync>>` for `cid::Error`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `multiaddr`.

To learn more, run the command again with --verbose.
```

Just thought I'd flag the build failure - it looks like #37 is addressing it.

### PR DESCRIPTION
**Pull request by kevincox**
Fixes #38

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Please merge asap, this blocks me because I use a crate that needs rust-mutiaddr.

**Comment by Yohe-Am** [comment]
+1 on merging this quick. I'm facing #38 as well.

**Comment by matthiasbeyer** [comment]
This PR is open for over a year now, I wouldn't put too much hope into it! :cry:

**Comment by Yohe-Am** [comment]
@matthiasbeyer yeah, I noticed that after commenting. [`parity-multiaddr`](https://lib.rs/parity-multiaddr) is a well maintained alternative for anyone looking.

**Comment by mxinden** [comment]
> @matthiasbeyer yeah, I noticed that after commenting. [`parity-multiaddr`](https://lib.rs/parity-multiaddr) is a well maintained alternative for anyone looking.

The two are now merged.

@Yohe-Am @matthiasbeyer sorry for the delay here. Let me know in case I can be of any additional help.

**Pull request closed without merging**
