### PR TITLE
fix: avoid allocations in `Display` and `Debug` of `Multiaddr`

### PR DESCRIPTION
**Pull request by hrxi**

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
This makes sense to me, thank you!

**Review by mxinden — COMMENTED** [review]
Cool! Did you stumble upon these in a memory profile?

If you want this as a patch release, mind bumping the version and adding a changelog entry?

**Comment by hrxi** [comment]
No, just happened to read these implementations by chance, and saw that they allocate. I remembered that we include them in a lot of log messages so I thought it might be worth sending a PR.

Should I also write a changelog entry if I don't need a patch release?

**Comment by mxinden** [comment]
> Should I also write a changelog entry if I don't need a patch release?

Fine without. Will be released whenever we cut a new release.

Thank you!

**Review by mxinden — APPROVED** [review]

**Pull request merged**
