### PR TITLE
CHANGELOG: Prepare v0.16.0

### PR DESCRIPTION
**Pull request by mxinden**
Unlocks https://github.com/libp2p/rust-libp2p/pull/2982.

Any objections by anyone? Anything else you would like to see included?

### CODE REVIEW

**Comment by mxinden** [comment]
//CC @John-LittleBearLabs

**Review by thomaseizinger — APPROVED** [review]

**Comment by mxinden** [comment]
Friendly ping @dignifiedquire as the _Captain_ of the project.

On a related note, I am happy to officially co-maintain this project @dignifiedquire if you would like help.

**Comment by elenaf9** [comment]
If this is not super urgent I'd like to include the changes proposed in https://github.com/multiformats/multiaddr/pull/147, for which I will do a PR on rust-multiaddr in the next days. Since libp2p/rust-libp2p#2289 is blocked on it I'd like to have it included in this release.

**Comment by mxinden** [comment]
> If this is not super urgent I'd like to include the changes proposed in [multiformats/multiaddr#147](https://github.com/multiformats/multiaddr/pull/147), for which I will do a PR on rust-multiaddr in the next days. Since [libp2p/rust-libp2p#2289](https://github.com/libp2p/rust-libp2p/pull/2289) is blocked on it I'd like to have it included in this release.

I suggest we don't block on your upcoming pull request to add `/quic-v1` here. In case it makes it in time, great. In case it doesn't, I am happy to cut another release right after your upcoming pull request has been merged.

**Comment by marten-seemann** [comment]
> > If this is not super urgent I'd like to include the changes proposed in [multiformats/multiaddr#147](https://github.com/multiformats/multiaddr/pull/147), for which I will do a PR on rust-multiaddr in the next days. Since [libp2p/rust-libp2p#2289](https://github.com/libp2p/rust-libp2p/pull/2289) is blocked on it I'd like to have it included in this release.
> 
> I suggest we don't block on your upcoming pull request to add `/quic-v1` here. In case it makes it in time, great. In case it doesn't, I am happy to cut another release right after your upcoming pull request has been merged.

It would be a very sad state of affairs if the existing QUIC code point was used for nodes that _only_ speak QUIC v1. Currently, we have the property that every node that advertises the existing code point speaks QUIC draft-29 (and _potentially_ QUIC v1 **in addition**).

**Comment by marten-seemann** [comment]
Not sure if I was commenting on the right issue, or if my comment even makes sense in this repo ;)

I just meant to caution against rolling out rust-libp2p with QUIC support using the existing code point, given that we seem to be converging on minting a new code point for QUIC v1.

**Comment by mxinden** [comment]
> Not sure if I was commenting on the right issue, or if my comment even makes sense in this repo ;)

This release only releases https://github.com/multiformats/rust-multiaddr/pull/60.

Whether to block https://github.com/libp2p/rust-libp2p/pull/2289 on https://github.com/multiformats/multiaddr/pull/147 is orthogonal to this release.

Your comment is important @marten-seemann. I suggest to move it to https://github.com/libp2p/rust-libp2p/pull/2289 or https://github.com/multiformats/multiaddr/pull/147

**Review by dignifiedquire — APPROVED** [review]

**Comment by mxinden** [comment]
[Tagged](https://github.com/multiformats/rust-multiaddr/releases/tag/v0.16.0) and [published](https://crates.io/crates/multiaddr/0.16.0).

**Pull request merged**
